name: Deploy to AWS ECS

# Only trigger, when the build workflow succeeded
on:
  push:
    tags:
      - '*.*'
  workflow_run:
    workflows: ["Docker CI"]
    types:
      - completed

env:
  AWS_REGION: us-east-1                                                           # set this to your preferred AWS region, e.g. us-west-1
  ECS_SERVICE: alura-service-devops                                               # set this to your Amazon ECS service name
  ECS_CLUSTER: alura-devop-challenge                                             # set this to your Amazon ECS cluster name
  CONTAINER_NAME: docker-cleberrangeljr                                           # set this to the name of the container in the
                                                                                  # containerDefinitions section of your task definition
  DOCKER_IMAGE_NAME: cleberrangeljr/alura-devops-challenge:${{github.ref_name}}   # docker hub repo

jobs:
  deploy:
    name: Deploy to AWS ECS
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ECS_ACESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_ECS_SECRET_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Running tasks
        uses: donaldpiret/ecs-deploy@master
        with:
          cluster: ${{env.ECS_CLUSTER}}
          target: ${{env.ECS_SERVICE}}
          image: docker-cleberrangeljr ${{env.DOCKER_IMAGE_NAME}}