name: Docker CI

# Controls when the workflow will run
on:
  push:
    tags:
      - '*.*'

# A workflow run is made up of one or more jobs
jobs:
  build:
    runs-on: ubuntu-latest   # The type of runner that the job will run on

     # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout
        uses: actions/checkout@v3 # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      
      - name: Set up Docker build
        uses: docker/setup-buildx-action@v1
      
      - name: Build and Push to Docker
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/alura-devops-challenge:${{github.ref_name}}

      - name: Push to ECS service
        uses: ./.github/workflows/aws_deploy
        with:
          version-tag: ${{github.ref_name}}

  


